/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KUKUH
 */
import entity.Proyek;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;


public class proyek extends javax.swing.JFrame {

    /**
     * Creates new form proyek
     */
    public proyek() {
        initComponents();
        loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        save = new java.awt.Button();
        button3 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button2 = new java.awt.Button();
        button4 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("proyek");

        jLabel2.setText("nama");

        jLabel3.setText("lokasi");

        jLabel4.setText("tanggal mulai");

        jLabel5.setText("tanggal selesai");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        button1.setLabel("delete");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        save.setLabel("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        button3.setLabel("edit");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        button2.setLabel("clear");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button4.setLabel("Print");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField9)
                            .addComponent(jTextField8)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    String namaProyek = jTextField1.getText();
    String lokasi = jTextField2.getText();
    String tanggalMulai = jTextField8.getText();  
    String tanggalSelesai = jTextField9.getText(); 

    // Konfigurasi Hibernate
    Configuration cfg = new Configuration().configure().addAnnotatedClass(Proyek.class);
    SessionFactory factory = cfg.buildSessionFactory();

    // Membuka sesi Hibernate
    Session session = factory.getCurrentSession();
    try {
        // Membuat objek Proyek baru
        Proyek proyek = new Proyek();
        proyek.setNamaproyek(namaProyek);
        proyek.setLokasi(lokasi);
        proyek.setTanggalmulai(tanggalMulai);
        proyek.setTanggalselesai(tanggalSelesai);

        // Mulai transaksi
        Transaction transaction = session.beginTransaction();
        session.save(proyek);  // Menyimpan objek ke database
        transaction.commit();  // Commit transaksi

        JOptionPane.showMessageDialog(null, "Proyek berhasil ditambahkan!");
        loadData();

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menambahkan proyek.");
    } finally {
        session.close();  // Tutup sesi
        factory.close();  // Tutup sesi factory
    }
    }//GEN-LAST:event_saveActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        String namaProyek = jTextField1.getText();
        String lokasi = jTextField2.getText();
        String tanggalMulai = jTextField8.getText();  
        String tanggalSelesai = jTextField9.getText(); 

    // Konfigurasi Hibernate
    Configuration cfg = new Configuration().configure().addAnnotatedClass(Proyek.class);
    SessionFactory factory = cfg.buildSessionFactory();

    // Membuka sesi Hibernate
    Session session = factory.getCurrentSession();
    try {
            // Ambil ID atau nama proyek untuk menemukan proyek yang ingin diedit
            String proyekNama = jTextField1.getText();  // As an example, using 'namaProyek' for search

            // Begin transaction
            session.beginTransaction();

            // Retrieve the existing Proyek object using its identifier (assuming 'namaProyek' is unique)
            Proyek proyek = (Proyek) session.createQuery("FROM Proyek WHERE namaProyek = :proyekNama")
                    .setParameter("proyekNama", proyekNama)
                    .uniqueResult();

            if (proyek != null) {
                // Update the retrieved Proyek object with new values from the text fields
                proyek.setLokasi(lokasi);
                proyek.setTanggalmulai(tanggalMulai);
                proyek.setTanggalselesai(tanggalSelesai);

                // Commit the transaction to update the record in the database
                session.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Proyek berhasil diupdate!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Proyek dengan nama " + proyekNama + " tidak ditemukan.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengupdate proyek.");
        } finally {
            session.close();  // Tutup sesi
            factory.close();  // Tutup sesi factory
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String namaProyek = jTextField1.getText();

    // Check if the project name is not empty
    if (namaProyek == null || namaProyek.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama proyek tidak boleh kosong!");
        return;
    }

    // Configure Hibernate
    Configuration cfg = new Configuration().configure().addAnnotatedClass(Proyek.class);
    SessionFactory factory = cfg.buildSessionFactory();
    Session session = factory.getCurrentSession();

    try {
        // Begin transaction
        Transaction transaction = session.beginTransaction();

        // Retrieve the Proyek object by name
        Proyek proyekToDelete = (Proyek) session.createQuery("FROM Proyek WHERE namaProyek = :namaProyek")
                                                .setParameter("namaProyek", namaProyek)
                                                .uniqueResult();

        if (proyekToDelete != null) {
            // If the project is found, delete it
            session.delete(proyekToDelete);
            transaction.commit();  // Commit transaction
            JOptionPane.showMessageDialog(null, "Proyek berhasil dihapus!");
            loadData();
        } else {
            JOptionPane.showMessageDialog(null, "Proyek tidak ditemukan!");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus proyek.");
    } finally {
        session.close();  // Close session
        factory.close();  // Close factory
    }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
    }//GEN-LAST:event_button2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // Mendapatkan baris yang diklik
    int selectedRow = jTable1.getSelectedRow();
    
    // Ambil data dari baris yang dipilih dan kolom tertentu
    String namaProyek = jTable1.getValueAt(selectedRow, 0).toString();
    String lokasi = jTable1.getValueAt(selectedRow, 1).toString();
    String tanggalMulai = jTable1.getValueAt(selectedRow, 2).toString();
    String tanggalSelesai = jTable1.getValueAt(selectedRow, 3).toString();

    // Set data ke JTextField
    jTextField1.setText(namaProyek);
    jTextField2.setText(lokasi);
    jTextField8.setText(tanggalMulai);
    jTextField9.setText(tanggalSelesai);
    }//GEN-LAST:event_jTable1MouseClicked

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
         try {
    // Path absolut ke file report1.jrxml
    String reportPath = "C:\\Users\\KUKUH\\OneDrive\\Documents\\NetBeansProjects\\tes\\src\\reports\\report1.jrxml";

    // Compile file JRXML menjadi file Jasper
    JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);

    // Parameter (jika ada, jika tidak kosongkan)
    java.util.Map<String, Object> parameters = new java.util.HashMap<>();
    parameters.put("ParameterName", "Value");

    // Hibernate session untuk data
    Configuration cfg = new Configuration().configure().addAnnotatedClass(Proyek.class);
    SessionFactory factory = cfg.buildSessionFactory();
    Session session = factory.openSession();
    session.beginTransaction();
    List<Proyek> proyekList = session.createQuery("FROM Proyek").list();
    session.getTransaction().commit();
    session.close();

    // Data source dari Hibernate
    JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(proyekList);

    // Isi laporan dengan data dan parameter
    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, dataSource);

    // Tampilkan laporan di JasperViewer
    JasperViewer.viewReport(jasperPrint, false);

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage());
}
    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadData() {
    // Konfigurasi Hibernate
    Configuration cfg = new Configuration().configure().addAnnotatedClass(Proyek.class);
    SessionFactory factory = cfg.buildSessionFactory();
    Session session = factory.openSession();

    try {
        // Mulai transaksi
        session.beginTransaction();

        // Ambil semua data dari tabel Proyek
        List<Proyek> proyekList = session.createQuery("FROM Proyek").list();

        // Buat model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Nama Proyek", "Lokasi", "Tanggal Mulai", "Tanggal Selesai"});

        // Tambahkan data ke model tabel
        for (Proyek proyek : proyekList) {
            model.addRow(new Object[]{
                proyek.getNamaproyek(),
                proyek.getLokasi(),
                proyek.getTanggalmulai(),
                proyek.getTanggalselesai()
            });
        }

        // Set model ke JTable
        jTable1.setModel(model);

        session.getTransaction().commit();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat data proyek.");
    } finally {
        session.close();  // Tutup sesi
        factory.close();  // Tutup sesi factory
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Button save;
    // End of variables declaration//GEN-END:variables
}
